version: '3.8'

services:
  app:
    build:
      context: .
      target: final
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      API_URL_SENTIMENT: ${API_URL_SENTIMENT}
      API_URL_FRONT: ${API_URL_FRONT}
    secrets:
      - db_password

secrets:
  db_password:
    file: ./secrets/db_password