name: Main Branch workflow

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'recette'
        run: |
          echo "ERROR: You can only merge to main from recette."
          exit 0

  build:
    needs: check_branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        mkdir -p secrets
        echo "${{ secrets.DB_PASSWORD_PROD }}" > secrets/db_password
        docker build --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD_PROD }} -t cicdm1 .
        docker push cicdm1