name: Main Branch workflow

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'recette'
        run: |
          echo "ERROR: You can only merge to main from recette."
          exit 0

  build:
    needs: check_branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        mkdir -p secrets
        echo "${{ secrets.DB_PASSWORD_PROD }}" > secrets/db_password
        docker build --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD_PROD }} -t djlopezz/cicdm1 .
        docker push djlopezz/cicdm1
  
  website-ready:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Wait for website to be ready
      run: |
        for i in {1..30}; do
          if curl -sSf "https://cicdm1.onrender.com" > /dev/null; then
            echo "Website is ready!";
            exit 0;
          fi;
          echo "Waiting for website...";
          sleep 5;
        done;
        echo "Website did not become ready in time.";
        exit 1;
  
  load-test:
    runs-on: ubuntu-latest
    needs: [Hook, website-ready]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trigger GitHub Hook
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/ynov-2025-m1-team7/CICD_M1_LOAD_TESTING/dispatches \
        -d '{"event_type": "load-test-trigger"}'

    - name: Upload summary.json
      uses: actions/upload-artifact@v3
      with:
        name: load-test-summary
        path: summary.json

  Hook:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: refresh webservice
      run: |
        curl -X POST "${{ secrets.RENDER_HOOK_URL }}"

  test:
    runs-on: ubuntu-latest
    needs: [load-test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Wait for website to be ready
      run: |
        for i in {1..30}; do
          if curl -sSf "https://cicdm1.onrender.com" > /dev/null; then
            echo "Website is ready!";
            exit 0;
          fi;
          echo "Waiting for website...";
          sleep 5;
        done;
        echo "Website did not become ready in time.";
        exit 1;

    - name: Run tests
      run: |
        go test ./... -v > test-results.txt

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.txt